# Generated by Django 5.0.7 on 2024-07-18 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('cardID', models.AutoField(primary_key=True, serialize=False)),
                ('surah', models.CharField(blank=True, max_length=255, null=True)),
                ('vrse', models.CharField(blank=True, max_length=255, null=True)),
                ('dateTime', models.DateTimeField()),
                ('level', models.CharField(blank=True, choices=[('excellent', 'excellent'), ('good', 'good'), ('average', 'average'), ('repeat', 'repeat')], max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dateTime'],
            },
        ),
    ]
