# Generated by Django 5.0.7 on 2024-07-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={},
        ),
        migrations.AddField(
            model_name='cards',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cards',
            name='dateTime',
            field=models.DateField(),
        ),
    ]
