# Generated by Django 5.0.7 on 2024-07-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_cards_options_cards_complete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'ordering': ['dateTime']},
        ),
        migrations.AlterField(
            model_name='cards',
            name='surah',
            field=models.CharField(blank=True, choices=[('Al-Fatihah', 'Al-Fatihah'), ('Al-Baqarah', 'Al-Baqarah'), ('Aal-E-Imran', 'Aal-E-Imran'), ('An-Nisa', 'An-Nisa'), ("Al-Ma'idah", "Al-Ma'idah"), ("Al-An'am", "Al-An'am"), ("Al-A'raf", "Al-A'raf"), ('Al-Anfal', 'Al-Anfal'), ('At-Tawbah', 'At-Tawbah'), ('Yunus', 'Yunus'), ('Hud', 'Hud'), ('Yusuf', 'Yusuf'), ("Ar-Ra'd", "Ar-Ra'd"), ('Ibrahim', 'Ibrahim'), ('Al-Hijr', 'Al-Hijr'), ('An-Nahl', 'An-Nahl'), ('Al-Isra', 'Al-Isra'), ('Al-Kahf', 'Al-Kahf'), ('Maryam', 'Maryam'), ('Ta-Ha', 'Ta-Ha'), ('Al-Anbiya', 'Al-Anbiya'), ('Al-Hajj', 'Al-Hajj'), ("Al-Mu'minun", "Al-Mu'minun"), ('An-Nur', 'An-Nur'), ('Al-Furqan', 'Al-Furqan'), ("Ash-Shu'ara", "Ash-Shu'ara"), ('An-Naml', 'An-Naml'), ('Al-Qasas', 'Al-Qasas'), ('Al-Ankabut', 'Al-Ankabut'), ('Ar-Rum', 'Ar-Rum'), ('Luqman', 'Luqman'), ('As-Sajda', 'As-Sajda'), ('Al-Ahzab', 'Al-Ahzab'), ('Saba', 'Saba'), ('Fatir', 'Fatir'), ('Ya-Sin', 'Ya-Sin'), ('As-Saffat', 'As-Saffat'), ('Sad', 'Sad'), ('Az-Zumar', 'Az-Zumar'), ('Ghafir', 'Ghafir'), ('Fussilat', 'Fussilat'), ('Ash-Shura', 'Ash-Shura'), ('Az-Zukhruf', 'Az-Zukhruf'), ('Ad-Dukhan', 'Ad-Dukhan'), ('Al-Jathiya', 'Al-Jathiya'), ('Al-Ahqaf', 'Al-Ahqaf'), ('Muhammad', 'Muhammad'), ('Al-Fath', 'Al-Fath'), ('Al-Hujurat', 'Al-Hujurat'), ('Qaf', 'Qaf'), ('Adh-Dhariyat', 'Adh-Dhariyat'), ('At-Tur', 'At-Tur'), ('An-Najm', 'An-Najm'), ('Al-Qamar', 'Al-Qamar'), ('Ar-Rahman', 'Ar-Rahman'), ('Al-Waqia', 'Al-Waqia'), ('Al-Hadid', 'Al-Hadid'), ('Al-Mujadila', 'Al-Mujadila'), ('Al-Hashr', 'Al-Hashr'), ('Al-Mumtahina', 'Al-Mumtahina'), ('As-Saff', 'As-Saff'), ('Al-Jumua', 'Al-Jumua'), ('Al-Munafiqun', 'Al-Munafiqun'), ('At-Taghabun', 'At-Taghabun'), ('At-Talaq', 'At-Talaq'), ('At-Tahrim', 'At-Tahrim'), ('Al-Mulk', 'Al-Mulk'), ('Al-Qalam', 'Al-Qalam'), ('Al-Haaqqa', 'Al-Haaqqa'), ("Al-Ma'arij", "Al-Ma'arij"), ('Nuh', 'Nuh'), ('Al-Jinn', 'Al-Jinn'), ('Al-Muzzammil', 'Al-Muzzammil'), ('Al-Muddathir', 'Al-Muddathir'), ('Al-Qiyama', 'Al-Qiyama'), ('Al-Insan', 'Al-Insan'), ('Al-Mursalat', 'Al-Mursalat'), ('An-Naba', 'An-Naba'), ("An-Nazi'at", "An-Nazi'at"), ('Abasa', 'Abasa'), ('At-Takwir', 'At-Takwir'), ('Al-Infitar', 'Al-Infitar'), ('Al-Mutaffifin', 'Al-Mutaffifin'), ('Al-Inshiqaq', 'Al-Inshiqaq'), ('Al-Buruj', 'Al-Buruj'), ('At-Tariq', 'At-Tariq'), ('Al-Ala', 'Al-Ala'), ('Al-Ghashiya', 'Al-Ghashiya'), ('Al-Fajr', 'Al-Fajr'), ('Al-Balad', 'Al-Balad'), ('Ash-Shams', 'Ash-Shams'), ('Al-Lail', 'Al-Lail'), ('Ad-Duhaa', 'Ad-Duhaa'), ('Ash-Sharh', 'Ash-Sharh'), ('At-Tin', 'At-Tin'), ('Al-Alaq', 'Al-Alaq'), ('Al-Qadr', 'Al-Qadr'), ('Al-Bayyina', 'Al-Bayyina'), ('Az-Zalzala', 'Az-Zalzala'), ('Al-Adiyat', 'Al-Adiyat'), ('Al-Qaria', 'Al-Qaria'), ('At-Takathur', 'At-Takathur'), ('Al-Asr', 'Al-Asr'), ('Al-Humaza', 'Al-Humaza'), ('Al-Fil', 'Al-Fil'), ('Quraish', 'Quraish'), ("Al-Ma'un", "Al-Ma'un"), ('Al-Kawthar', 'Al-Kawthar'), ('Al-Kafiroon', 'Al-Kafiroon'), ('An-Nasr', 'An-Nasr'), ('Al-Masad', 'Al-Masad'), ('Al-Ikhlas', 'Al-Ikhlas'), ('Al-Falaq', 'Al-Falaq'), ('An-Nas', 'An-Nas')], max_length=255, null=True),
        ),
    ]
