# # from django.db import models
# # from django.contrib.auth.models import User
# # # Create your models here.

# # class Cards(models.Model):
# #     levelValues = [
# #         ('excellent','excellent'),
# #         ('good','good'),
# #         ('average','average'),
# #         ('repeat','repeat'),
# #     ]
# #     user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
# #     cardID = models.AutoField(primary_key=True)
# #     surah = models.CharField(max_length=255, null=True, blank=True)
# #     vrse = models.CharField(max_length=255, null=True, blank=True)
# #     dateTime = models.DateField()
# #     level = models.CharField(max_length=50, null=True, blank=True, choices=levelValues)
# #     complete = models.BooleanField(default=False)
# #     def __str__(self):
# #         # return self.cardID
# #         return f"{self.surah} - {self.vrse}"
    
# #     class Meta:
# #         ordering = ['dateTime']
# from django.db import models
# from django.contrib.auth.models import User

# class Cards(models.Model):
#     levelValues = [
#         ('excellent', 'excellent'),
#         ('good', 'good'),
#         ('average', 'average'),
#         ('repeat', 'repeat'),
#     ]
#     surahs = [
#         ("Al-Fatihah", "Al-Fatihah"),
#         ("Al-Baqarah", "Al-Baqarah"),
#         ("Aal-E-Imran", "Aal-E-Imran"),
#         ("An-Nisa", "An-Nisa"),
#         ("Al-Ma'idah", "Al-Ma'idah"),
#         ("Al-An'am", "Al-An'am"),
#         ("Al-A'raf", "Al-A'raf"),
#         ("Al-Anfal", "Al-Anfal"),
#         ("At-Tawbah", "At-Tawbah"),
#         ("Yunus", "Yunus"),
#         ("Hud", "Hud"),
#         ("Yusuf", "Yusuf"),
#         ("Ar-Ra'd", "Ar-Ra'd"),
#         ("Ibrahim", "Ibrahim"),
#         ("Al-Hijr", "Al-Hijr"),
#         ("An-Nahl", "An-Nahl"),
#         ("Al-Isra", "Al-Isra"),
#         ("Al-Kahf", "Al-Kahf"),
#         ("Maryam", "Maryam"),
#         ("Ta-Ha", "Ta-Ha"),
#         ("Al-Anbiya", "Al-Anbiya"),
#         ("Al-Hajj", "Al-Hajj"),
#         ("Al-Mu'minun", "Al-Mu'minun"),
#         ("An-Nur", "An-Nur"),
#         ("Al-Furqan", "Al-Furqan"),
#         ("Ash-Shu'ara", "Ash-Shu'ara"),
#         ("An-Naml", "An-Naml"),
#         ("Al-Qasas", "Al-Qasas"),
#         ("Al-Ankabut", "Al-Ankabut"),
#         ("Ar-Rum", "Ar-Rum"),
#         ("Luqman", "Luqman"),
#         ("As-Sajda", "As-Sajda"),
#         ("Al-Ahzab", "Al-Ahzab"),
#         ("Saba", "Saba"),
#         ("Fatir", "Fatir"),
#         ("Ya-Sin", "Ya-Sin"),
#         ("As-Saffat", "As-Saffat"),
#         ("Sad", "Sad"),
#         ("Az-Zumar", "Az-Zumar"),
#         ("Ghafir", "Ghafir"),
#         ("Fussilat", "Fussilat"),
#         ("Ash-Shura", "Ash-Shura"),
#         ("Az-Zukhruf", "Az-Zukhruf"),
#         ("Ad-Dukhan", "Ad-Dukhan"),
#         ("Al-Jathiya", "Al-Jathiya"),
#         ("Al-Ahqaf", "Al-Ahqaf"),
#         ("Muhammad", "Muhammad"),
#         ("Al-Fath", "Al-Fath"),
#         ("Al-Hujurat", "Al-Hujurat"),
#         ("Qaf", "Qaf"),
#         ("Adh-Dhariyat", "Adh-Dhariyat"),
#         ("At-Tur", "At-Tur"),
#         ("An-Najm", "An-Najm"),
#         ("Al-Qamar", "Al-Qamar"),
#         ("Ar-Rahman", "Ar-Rahman"),
#         ("Al-Waqia", "Al-Waqia"),
#         ("Al-Hadid", "Al-Hadid"),
#         ("Al-Mujadila", "Al-Mujadila"),
#         ("Al-Hashr", "Al-Hashr"),
#         ("Al-Mumtahina", "Al-Mumtahina"),
#         ("As-Saff", "As-Saff"),
#         ("Al-Jumua", "Al-Jumua"),
#         ("Al-Munafiqun", "Al-Munafiqun"),
#         ("At-Taghabun", "At-Taghabun"),
#         ("At-Talaq", "At-Talaq"),
#         ("At-Tahrim", "At-Tahrim"),
#         ("Al-Mulk", "Al-Mulk"),
#         ("Al-Qalam", "Al-Qalam"),
#         ("Al-Haaqqa", "Al-Haaqqa"),
#         ("Al-Ma'arij", "Al-Ma'arij"),
#         ("Nuh", "Nuh"),
#         ("Al-Jinn", "Al-Jinn"),
#         ("Al-Muzzammil", "Al-Muzzammil"),
#         ("Al-Muddathir", "Al-Muddathir"),
#         ("Al-Qiyama", "Al-Qiyama"),
#         ("Al-Insan", "Al-Insan"),
#         ("Al-Mursalat", "Al-Mursalat"),
#         ("An-Naba", "An-Naba"),
#         ("An-Nazi'at", "An-Nazi'at"),
#         ("Abasa", "Abasa"),
#         ("At-Takwir", "At-Takwir"),
#         ("Al-Infitar", "Al-Infitar"),
#         ("Al-Mutaffifin", "Al-Mutaffifin"),
#         ("Al-Inshiqaq", "Al-Inshiqaq"),
#         ("Al-Buruj", "Al-Buruj"),
#         ("At-Tariq", "At-Tariq"),
#         ("Al-Ala", "Al-Ala"),
#         ("Al-Ghashiya", "Al-Ghashiya"),
#         ("Al-Fajr", "Al-Fajr"),
#         ("Al-Balad", "Al-Balad"),
#         ("Ash-Shams", "Ash-Shams"),
#         ("Al-Lail", "Al-Lail"),
#         ("Ad-Duhaa", "Ad-Duhaa"),
#         ("Ash-Sharh", "Ash-Sharh"),
#         ("At-Tin", "At-Tin"),
#         ("Al-Alaq", "Al-Alaq"),
#         ("Al-Qadr", "Al-Qadr"),
#         ("Al-Bayyina", "Al-Bayyina"),
#         ("Az-Zalzala", "Az-Zalzala"),
#         ("Al-Adiyat", "Al-Adiyat"),
#         ("Al-Qaria", "Al-Qaria"),
#         ("At-Takathur", "At-Takathur"),
#         ("Al-Asr", "Al-Asr"),
#         ("Al-Humaza", "Al-Humaza"),
#         ("Al-Fil", "Al-Fil"),
#         ("Quraish", "Quraish"),
#         ("Al-Ma'un", "Al-Ma'un"),
#         ("Al-Kawthar", "Al-Kawthar"),
#         ("Al-Kafiroon", "Al-Kafiroon"),
#         ("An-Nasr", "An-Nasr"),
#         ("Al-Masad", "Al-Masad"),
#         ("Al-Ikhlas", "Al-Ikhlas"),
#         ("Al-Falaq", "Al-Falaq"),
#         ("An-Nas", "An-Nas")
#     ]
#     surah_verse_counts = {
#         "Al-Fatihah": 7,
#         "Al-Baqarah": 286,
#         "Aal-E-Imran": 200,
#         "An-Nisa": 176,
#         "Al-Maidah": 120,
#         "Al-Anam": 165,
#         "Al-Araf": 206,
#         "Al-Anfal": 75,
#         "At-Tawbah": 129,
#         "Yunus": 109,
#         "Hud": 123,
#         "Yusuf": 111,
#         "Ar-Rad": 43,
#         "Ibrahim": 52,
#         "Al-Hijr": 99,
#         "An-Nahl": 128,
#         "Al-Isra": 111,
#         "Al-Kahf": 110,
#         "Maryam": 98,
#         "Taha": 135,
#         "Al-Anbiya": 112,
#         "Al-Hajj": 78,
#         "Al-Muminun": 118,
#         "An-Nur": 64,
#         "Al-Furqan": 77,
#         "Ash-Shuara": 227,
#         "An-Naml": 93,
#         "Al-Qasas": 88,
#         "Al-Ankabut": 69,
#         "Ar-Rum": 60,
#         "Luqman": 34,
#         "As-Sajda": 30,
#         "Al-Ahzab": 73,
#         "Saba": 54,
#         "Fatir": 45,
#         "Ya-Sin": 83,
#         "As-Saffat": 182,
#         "Sad": 88,
#         "Az-Zumar": 75,
#         "Ghafir": 85,
#         "Fussilat": 54,
#         "Ash-Shura": 53,
#         "Az-Zukhruf": 89,
#         "Ad-Dukhan": 59,
#         "Al-Jathiya": 37,
#         "Al-Ahqaf": 35,
#         "Muhammad": 38,
#         "Al-Fath": 29,
#         "Al-Hujurat": 18,
#         "Qaf": 45,
#         "Adh-Dhariyat": 60,
#         "At-Tur": 49,
#         "An-Najm": 62,
#         "Al-Qamar": 55,
#         "Ar-Rahman": 78,
#         "Al-Waqia": 96,
#         "Al-Hadid": 29,
#         "Al-Mujadila": 22,
#         "Al-Hashr": 24,
#         "Al-Mumtahina": 13,
#         "As-Saff": 14,
#         "Al-Jumu'a": 11,
#         "Al-Munafiqun": 11,
#         "At-Taghabun": 18,
#         "At-Talaq": 12,
#         "At-Tahrim": 12,
#         "Al-Mulk": 30,
#         "Al-Qalam": 52,
#         "Al-Haaqqa": 52,
#         "Al-Maarij": 44,
#         "Nuh": 28,
#         "Al-Jinn": 28,
#         "Al-Muzzammil": 20,
#         "Al-Muddaththir": 56,
#         "Al-Qiyama": 40,
#         "Al-Insan": 31,
#         "Al-Mursalat": 50,
#         "An-Naba": 40,
#         "An-Nazi'at": 46,
#         "Abasa": 42,
#         "At-Takwir": 29,
#         "Al-Infitar": 19,
#         "At-Tatfif": 36,
#         "Al-Inshiqaq": 25,
#         "Al-Buruj": 22,
#         "At-Tariq": 17,
#         "Al-A'la": 19,
#         "Al-Ghashiya": 26,
#         "Al-Fajr": 30,
#         "Al-Balad": 20,
#         "Ash-Shams": 15,
#         "Al-Lail": 21,
#         "Ad-Duha": 11,
#         "Ash-Sharh": 8,
#         "At-Tin": 8,
#         "Al-Alaq": 19,
#         "Al-Qadr": 5,
#         "Al-Bayyina": 8,
#         "Az-Zalzala": 8,
#         "Al-Adiyat": 11,
#         "Al-Qaria": 11,
#         "At-Takathur": 8,
#         "Al-Asr": 3,
#         "Al-Humaza": 9,
#         "Al-Fil": 5,
#         "Quraish": 4,
#         "Al-Ma'un": 7,
#         "Al-Kawthar": 3,
#         "Al-Kafirun": 6,
#         "An-Nasr": 3,
#         "Al-Masad": 5,
#         "Al-Ikhlas": 4,
#         "Al-Falaq": 5,
#         "An-Nas": 6
#     }

#     user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
#     cardID = models.AutoField(primary_key=True)
#     surah = models.CharField(max_length=255, null=True, blank=True, choices=surahs)
#     vrse = models.CharField(max_length=255, null=True, blank=True)
#     dateTime = models.DateField()
#     level = models.CharField(max_length=50, null=True, blank=True, choices=levelValues)
#     complete = models.BooleanField(default=False)

#     def __str__(self):
#         return f"{self.surah} - {self.vrse}"
    
#     class Meta:
#         ordering = ['dateTime']

from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db import models

# Example of Surah and their total verse count
surah_verse_counts = {
    "Al-Fatihah": 7,
    "Al-Baqarah": 286,
    "Aal-E-Imran": 200,
    "An-Nisa": 176,
    "Al-Maidah": 120,
    "Al-Anam": 165,
    "Al-Araf": 206,
    "Al-Anfal": 75,
    "At-Tawbah": 129,
    "Yunus": 109,
    "Hud": 123,
    "Yusuf": 111,
    "Ar-Rad": 43,
    "Ibrahim": 52,
    "Al-Hijr": 99,
    "An-Nahl": 128,
    "Al-Isra": 111,
    "Al-Kahf": 110,
    "Maryam": 98,
    "Taha": 135,
    "Al-Anbiya": 112,
    "Al-Hajj": 78,
    "Al-Muminun": 118,
    "An-Nur": 64,
    "Al-Furqan": 77,
    "Ash-Shuara": 227,
    "An-Naml": 93,
    "Al-Qasas": 88,
    "Al-Ankabut": 69,
    "Ar-Rum": 60,
    "Luqman": 34,
    "As-Sajda": 30,
    "Al-Ahzab": 73,
    "Saba": 54,
    "Fatir": 45,
    "Ya-Sin": 83,
    "As-Saffat": 182,
    "Sad": 88,
    "Az-Zumar": 75,
    "Ghafir": 85,
    "Fussilat": 54,
    "Ash-Shura": 53,
    "Az-Zukhruf": 89,
    "Ad-Dukhan": 59,
    "Al-Jathiya": 37,
    "Al-Ahqaf": 35,
    "Muhammad": 38,
    "Al-Fath": 29,
    "Al-Hujurat": 18,
    "Qaf": 45,
    "Adh-Dhariyat": 60,
    "At-Tur": 49,
    "An-Najm": 62,
    "Al-Qamar": 55,
    "Ar-Rahman": 78,
    "Al-Waqia": 96,
    "Al-Hadid": 29,
    "Al-Mujadila": 22,
    "Al-Hashr": 24,
    "Al-Mumtahina": 13,
    "As-Saff": 14,
    "Al-Jumu'a": 11,
    "Al-Munafiqun": 11,
    "At-Taghabun": 18,
    "At-Talaq": 12,
    "At-Tahrim": 12,
    "Al-Mulk": 30,
    "Al-Qalam": 52,
    "Al-Haaqqa": 52,
    "Al-Maarij": 44,
    "Nuh": 28,
    "Al-Jinn": 28,
    "Al-Muzzammil": 20,
    "Al-Muddaththir": 56,
    "Al-Qiyama": 40,
    "Al-Insan": 31,
    "Al-Mursalat": 50,
    "An-Naba": 40,
    "An-Nazi'at": 46,
    "Abasa": 42,
    "At-Takwir": 29,
    "Al-Infitar": 19,
    "At-Tatfif": 36,
    "Al-Inshiqaq": 25,
    "Al-Buruj": 22,
    "At-Tariq": 17,
    "Al-A'la": 19,
    "Al-Ghashiya": 26,
    "Al-Fajr": 30,
    "Al-Balad": 20,
    "Ash-Shams": 15,
    "Al-Lail": 21,
    "Ad-Duha": 11,
    "Ash-Sharh": 8,
    "At-Tin": 8,
    "Al-Alaq": 19,
    "Al-Qadr": 5,
    "Al-Bayyina": 8,
    "Az-Zalzala": 8,
    "Al-Adiyat": 11,
    "Al-Qaria": 11,
    "At-Takathur": 8,
    "Al-Asr": 3,
    "Al-Humaza": 9,
    "Al-Fil": 5,
    "Quraish": 4,
    "Al-Ma'un": 7,
    "Al-Kawthar": 3,
    "Al-Kafirun": 6,
    "An-Nasr": 3,
    "Al-Masad": 5,
    "Al-Ikhlas": 4,
    "Al-Falaq": 5,
    "An-Nas": 6
}

class Cards(models.Model):
    levelValues = [
        ('excellent', 'excellent'),
        ('good', 'good'),
        ('average', 'average'),
        ('repeat', 'repeat'),
    ]
    surahs = [
        ("Al-Fatihah", "Al-Fatihah"),
        ("Al-Baqarah", "Al-Baqarah"),
        ("Aal-E-Imran", "Aal-E-Imran"),
        ("An-Nisa", "An-Nisa"),
        ("Al-Ma'idah", "Al-Ma'idah"),
        ("Al-An'am", "Al-An'am"),
        ("Al-A'raf", "Al-A'raf"),
        ("Al-Anfal", "Al-Anfal"),
        ("At-Tawbah", "At-Tawbah"),
        ("Yunus", "Yunus"),
        ("Hud", "Hud"),
        ("Yusuf", "Yusuf"),
        ("Ar-Ra'd", "Ar-Ra'd"),
        ("Ibrahim", "Ibrahim"),
        ("Al-Hijr", "Al-Hijr"),
        ("An-Nahl", "An-Nahl"),
        ("Al-Isra", "Al-Isra"),
        ("Al-Kahf", "Al-Kahf"),
        ("Maryam", "Maryam"),
        ("Ta-Ha", "Ta-Ha"),
        ("Al-Anbiya", "Al-Anbiya"),
        ("Al-Hajj", "Al-Hajj"),
        ("Al-Mu'minun", "Al-Mu'minun"),
        ("An-Nur", "An-Nur"),
        ("Al-Furqan", "Al-Furqan"),
        ("Ash-Shu'ara", "Ash-Shu'ara"),
        ("An-Naml", "An-Naml"),
        ("Al-Qasas", "Al-Qasas"),
        ("Al-Ankabut", "Al-Ankabut"),
        ("Ar-Rum", "Ar-Rum"),
        ("Luqman", "Luqman"),
        ("As-Sajda", "As-Sajda"),
        ("Al-Ahzab", "Al-Ahzab"),
        ("Saba", "Saba"),
        ("Fatir", "Fatir"),
        ("Ya-Sin", "Ya-Sin"),
        ("As-Saffat", "As-Saffat"),
        ("Sad", "Sad"),
        ("Az-Zumar", "Az-Zumar"),
        ("Ghafir", "Ghafir"),
        ("Fussilat", "Fussilat"),
        ("Ash-Shura", "Ash-Shura"),
        ("Az-Zukhruf", "Az-Zukhruf"),
        ("Ad-Dukhan", "Ad-Dukhan"),
        ("Al-Jathiya", "Al-Jathiya"),
        ("Al-Ahqaf", "Al-Ahqaf"),
        ("Muhammad", "Muhammad"),
        ("Al-Fath", "Al-Fath"),
        ("Al-Hujurat", "Al-Hujurat"),
        ("Qaf", "Qaf"),
        ("Adh-Dhariyat", "Adh-Dhariyat"),
        ("At-Tur", "At-Tur"),
        ("An-Najm", "An-Najm"),
        ("Al-Qamar", "Al-Qamar"),
        ("Ar-Rahman", "Ar-Rahman"),
        ("Al-Waqia", "Al-Waqia"),
        ("Al-Hadid", "Al-Hadid"),
        ("Al-Mujadila", "Al-Mujadila"),
        ("Al-Hashr", "Al-Hashr"),
        ("Al-Mumtahina", "Al-Mumtahina"),
        ("As-Saff", "As-Saff"),
        ("Al-Jumua", "Al-Jumua"),
        ("Al-Munafiqun", "Al-Munafiqun"),
        ("At-Taghabun", "At-Taghabun"),
        ("At-Talaq", "At-Talaq"),
        ("At-Tahrim", "At-Tahrim"),
        ("Al-Mulk", "Al-Mulk"),
        ("Al-Qalam", "Al-Qalam"),
        ("Al-Haaqqa", "Al-Haaqqa"),
        ("Al-Ma'arij", "Al-Ma'arij"),
        ("Nuh", "Nuh"),
        ("Al-Jinn", "Al-Jinn"),
        ("Al-Muzzammil", "Al-Muzzammil"),
        ("Al-Muddathir", "Al-Muddathir"),
        ("Al-Qiyama", "Al-Qiyama"),
        ("Al-Insan", "Al-Insan"),
        ("Al-Mursalat", "Al-Mursalat"),
        ("An-Naba", "An-Naba"),
        ("An-Nazi'at", "An-Nazi'at"),
        ("Abasa", "Abasa"),
        ("At-Takwir", "At-Takwir"),
        ("Al-Infitar", "Al-Infitar"),
        ("Al-Mutaffifin", "Al-Mutaffifin"),
        ("Al-Inshiqaq", "Al-Inshiqaq"),
        ("Al-Buruj", "Al-Buruj"),
        ("At-Tariq", "At-Tariq"),
        ("Al-Ala", "Al-Ala"),
        ("Al-Ghashiya", "Al-Ghashiya"),
        ("Al-Fajr", "Al-Fajr"),
        ("Al-Balad", "Al-Balad"),
        ("Ash-Shams", "Ash-Shams"),
        ("Al-Lail", "Al-Lail"),
        ("Ad-Duhaa", "Ad-Duhaa"),
        ("Ash-Sharh", "Ash-Sharh"),
        ("At-Tin", "At-Tin"),
        ("Al-Alaq", "Al-Alaq"),
        ("Al-Qadr", "Al-Qadr"),
        ("Al-Bayyina", "Al-Bayyina"),
        ("Az-Zalzala", "Az-Zalzala"),
        ("Al-Adiyat", "Al-Adiyat"),
        ("Al-Qaria", "Al-Qaria"),
        ("At-Takathur", "At-Takathur"),
        ("Al-Asr", "Al-Asr"),
        ("Al-Humaza", "Al-Humaza"),
        ("Al-Fil", "Al-Fil"),
        ("Quraish", "Quraish"),
        ("Al-Ma'un", "Al-Ma'un"),
        ("Al-Kawthar", "Al-Kawthar"),
        ("Al-Kafiroon", "Al-Kafiroon"),
        ("An-Nasr", "An-Nasr"),
        ("Al-Masad", "Al-Masad"),
        ("Al-Ikhlas", "Al-Ikhlas"),
        ("Al-Falaq", "Al-Falaq"),
        ("An-Nas", "An-Nas")
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    cardID = models.AutoField(primary_key=True)
    surah = models.CharField(max_length=255, null=True, blank=True, choices=surahs)
    start_verse = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(1),MaxValueValidator(286)])
    end_verse = models.IntegerField(null=True, blank=True)
    dateTime = models.DateField()
    level = models.CharField(max_length=50, null=True, blank=True, choices=levelValues)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.surah} - {self.start_verse}-{self.end_verse}"

    def clean(self):
        # Get the total number of verses for the selected Surah
        total_verses = surah_verse_counts.get(self.surah)
        if not total_verses:
            raise ValidationError(f"Invalid Surah name: {self.surah}")
        # Check if the start and end verses are within the valid range
        if self.start_verse < 1 or self.end_verse > total_verses or self.start_verse > self.end_verse:
            raise ValidationError("The entered verse range is not valid for the selected Surah.")
    
    class Meta:
        ordering = ['dateTime']
